import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: 'Next.js Weekly Calendar (Open-Source)',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body>
      <nav className='w-full top-0 left-0 flex justify-between items-center header'>
        <div>
          <Link href='/'>
            <h1 className='text-4xl font-extrabold'>PadelPals</h1>
          </Link>
        </div>
        <div className='flex gap-x-5'>
          <Link href='/auth/log-in' className='text-xl'>Iniciar Sesión</Link>
          <Link href='/auth/sign-up' className='text-xl'>Registrarse</Link>
        </div>
      </nav>


      <div className="main">
          {children}
      </div>

      <Toaster/>

      </body>
      </html>
  )
}
