import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next.js Weekly Calendar (Open-Source)',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <head>
        <link rel="stylesheet" href="./globals.css"/>
      </head>
      <body>
      <div className="header">
          <h1><a href='https://code.daypilot.org/45330/next-js-weekly-calendar-open-source'>Next.js Weekly Calendar (Open-Source)</a></h1>
          <div><a href="https://javascript.daypilot.org/">DayPilot for JavaScript</a> - HTML5 Calendar/Scheduling Components for JavaScript/Angular/React/Vue</div>
      </div>

      <div className="main">
          {children}
      </div>

      </body>
      </html>
  )
}
